# Generated by Django 4.2.3 on 2023-08-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.CharField(default="Not Found", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="linkedin_url",
            field=models.URLField(default="Not Found"),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(default="Not Found", max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="products",
            field=models.TextField(default="Not Found"),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(default="Not Found"),
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("date", models.DateField()),
                ("notes", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.contact",
                    ),
                ),
            ],
        ),
    ]
